# -*- coding: utf-8 -*-
"""Brain_tumor_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFr5ly5Au9EfQyWEkr-Prp2kRKl3pNUl
"""

import tensorflow as tf
print("TensorFlow Version:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

!pip install -q opencv-python kaggle

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

print("TensorFlow:", tf.__version__)
print("OpenCV:", cv2.__version__)

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_path = "/content/Brain_humor.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Dataset extracted successfully!")

import os
print(os.listdir("/content/dataset"))

for root, dirs, files in os.walk("/content/dataset"):
    print(root)

#Define Dataset Paths
train_dir = "/content/dataset/Training"
test_dir = "/content/dataset/Testing"

"""## Check Number of Images in Each Class"""

import os

print("Training Dataset\n")

for folder in os.listdir(train_dir):
    count = len(os.listdir(os.path.join(train_dir, folder)))
    print(f"{folder}: {count} images")

print("\nTesting Dataset\n")

for folder in os.listdir(test_dir):
    count = len(os.listdir(os.path.join(test_dir, folder)))
    print(f"{folder}: {count} images")

"""## Display Sample MRI Images"""

import matplotlib.pyplot as plt
import cv2
classes = os.listdir(train_dir)
plt.figure(figsize=(16,4))

for i, cls in enumerate(classes):
    img_path = os.path.join(train_dir, cls, os.listdir(os.path.join(train_dir, cls))[0])

    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(1,4,i+1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

"""## Check Image Size"""

img = cv2.imread(img_path)
print("Image Shape:", img.shape)

"""## Training Data Generator"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    validation_split=0.2
)

"""###Validation Data Generator"""

validation_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

#testing data generator
test_datagen = ImageDataGenerator(
    rescale=1./255
)

"""##load the Dataset"""

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

validation_generator = validation_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

## testing set
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

print(train_generator.class_indices)

print("Training Samples:", train_generator.samples)
print("Validation Samples:", validation_generator.samples)
print("Testing Samples:", test_generator.samples)

# Load pre-trained EfficientNetB0 without the top classification layer
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Freeze the base model layers to preserve pre-trained features
base_model.trainable = False

# Reconstruct the top head for 4 classes
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(4, activation='softmax')(x) # 4 classes: glioma, meningioma, notumor, pituitary

# Final Model
model = Model(inputs=base_model.input, outputs=predictions)

# Compile Model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Setup your imported callbacks
callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_brain_tumor_model.keras', monitor='val_loss', save_best_only=True)
]

# Train
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20,
    callbacks=callbacks
)

"""## Model Configuration & Hyperparameters"""

# Model Configurations
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 20
NUM_CLASSES = 4

# Train generator with data augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode="nearest"
)

# Test generator should only scale (no augmentation)
test_datagen = ImageDataGenerator(rescale=1./255)

# Flow from directory
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

"""## Transfer Learning Model"""

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss Plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

## Evaluate on Test Data
test_loss, test_acc = model.evaluate(test_generator)
print(f"\n🎯 Final Testing Accuracy: {test_acc*100:.2f}%")
print(f"📉 Final Testing Loss: {test_loss:.4f}")

model.save('brain_tumor_model.keras')
from google.colab import files
files.download('brain_tumor_model.keras')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# tensorflow
# gradio
# pillow
# numpy



import gradio as gr
import tensorflow as tf
from PIL import Image
import numpy as np
model = tf.keras.models.load_model('brain_tumor_model.keras')
class_names = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']

def predict_tumor(image):
    image = image.resize((224, 224))
    img_array = np.array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    predictions = model.predict(img_array)[0]
    return {class_names[i]: float(predictions[i]) for i in range(len(class_names))}
interface = gr.Interface(
    fn=predict_tumor,
    inputs=gr.Image(type="pil", label="Upload Brain MRI Scan"),
    outputs=gr.Label(num_top_classes=4, label="Prediction Results"),
    title="Brain Tumor Classification System",
    description="Upload a Brain MRI image to detect the type of tumor (Glioma, Meningioma, Pituitary, or No Tumor) using a fine-tuned EfficientNetB0 model."
)

if __name__ == "__main__":
    interface.launch()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import gradio as gr
# import tensorflow as tf
# from PIL import Image
# import numpy as np
# 
# model = tf.keras.models.load_model('best_brain_tumor_model.keras')
# class_names = ['Glioma', 'Meningioma', 'No Tumor', 'Pituitary']
# 
# def predict_tumor(image):
#     image = image.resize((224, 224))
#     img_array = np.array(image) / 255.0
#     img_array = np.expand_dims(img_array, axis=0)
#     predictions = model.predict(img_array)[0]
#     return {class_names[i]: float(predictions[i]) for i in range(len(class_names))}
# 
# interface = gr.Interface(
#     fn=predict_tumor,
#     inputs=gr.Image(type="pil", label="Upload Brain MRI Scan"),
#     outputs=gr.Label(num_top_classes=4, label="Prediction Results"),
#     title="Brain Tumor Classification System",
#     description="Upload a Brain MRI image to detect the type of tumor."
# )
# 
# if __name__ == "__main__":
#     interface.launch()









