# -*- coding: utf-8 -*-
"""Movie_recom_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16RSArjPrTzhCELZjRobnE4UoS3PY_UGI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

genome_score=pd.read_csv("data/genome_scores.csv")
genome_tags=pd.read_csv("data/genome_tags.csv")
links=pd.read_csv("data/link.csv")
movies=pd.read_csv("data/movie.csv")
ratings=pd.read_csv("data/rating.csv")
tags=pd.read_csv("data/tag.csv")

data = ratings.merge(movies, on="movieId")

ratings=pd.merge(ratings,movies, on='movieId')

movies=pd.merge(movies,links, on='movieId')

content = movies.merge(tags, on="movieId", how="left")

genome = genome_score.merge(genome_tags, on="tagId")

data.head()

content.head()

genome.head()

user_movie_matrix = data.pivot_table(
    index="userId",
    columns="title",
    values="rating"
)

user_movie_matrix = user_movie_matrix.fillna(0)

user_movie_matrix

from sklearn.metrics.pairwise import cosine_similarity
similarity= cosine_similarity(user_movie_matrix.T)

"""## Create similarity DataFrame"""

similarity_df=pd.DataFrame(similarity, index=user_movie_matrix.columns, columns=user_movie_matrix.columns)

"""## Build recommendation function"""

def recommend(movie_name):
    if movie_name not in similarity_df.columns:
        return "Movie not found"

    similar_movies = similarity_df[movie_name].sort_values(ascending=False)[1:6]
    return similar_movies

"""## Test"""

recommend("Toy Story (1995)")

user_movie_matrix.shape

cosine_similarity(user_movie_matrix.T)

movies = movies[["movieId", "title", "genres"]]
tags = tags[["movieId", "tag"]]

"""## Combine tags per movie"""

tags_grouped = tags.groupby("movieId")["tag"].apply(lambda x: " ".join(x.dropna().astype(str))).reset_index()

"""## Merge movies + tags"""

content_data=pd.merge(movies, tags_grouped, on="movieId", how="left")

content_data["tag"]=content_data["tag"].fillna("")

#create final feature
content_data["content"] = content_data["genres"] + " " + content_data["tag"]

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")
matrix = tfidf.fit_transform(content_data["content"])

"""## Compute Similarity"""

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(matrix)

"""## Build index mapping"""

indices = pd.Series(content_data.index, index=content_data["title"]).drop_duplicates()

##Recommendation function
def recommend_content(movie_title):
    if movie_title not in indices:
        return "Movie not found"

    idx = indices[movie_title]

    sim_scores = list(enumerate(similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:6]

    movie_indices = [i[0] for i in sim_scores]

    return content_data["title"].iloc[movie_indices]

recommend_content("Toy Story (1995)")

collab_movies = recommend("Toy Story (1995)")
content_movies = recommend_content("Toy Story (1995)")

#Display Both
print("Collaborative Filtering Recommendations:")
print(collab_movies)
print("\nContent-Based Filtering Recommendations:")
print(content_movies)

def hybrid_recommend(movie_name, top_n=10):
    collab = list(recommend(movie_name).index)
    content = list(recommend_content(movie_name))

    # Combine recommendations
    hybrid = []

    for movie in collab:
        if movie not in hybrid:
            hybrid.append(movie)

    for movie in content:
        if movie not in hybrid:
            hybrid.append(movie)

    return hybrid[:top_n]

hybrid_recommend("Toy Story (1995)")

movie_stats = data.groupby("title")["rating"].agg(["mean", "count"])
popular_movies = movie_stats[movie_stats["count"] >= 50]
popular_movies.sort_values("mean", ascending=False).head(10)

"""## Add Movie Posters"""

links=pd.read_csv("data/link.csv")



























